version: '3'

volumes:
  teamspeak-data:
     driver: local-persist
     driver_opts:
       mountpoint: ${CONTAINERVOLUME}/teamspeak
  teamspeak-db-data:
     driver: local-persist
     driver_opts:
       mountpoint: ${CONTAINERVOLUME}/var/lib/mysql

services:

  database:
    restart: always
    image: mariadb:10.4
    volumes:
      - teamspeak-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  application:
    restart: always
    image: teamspeak
    depends_on:
      - database
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: database
      TS3SERVER_DB_USER: ${MYSQL_USER}
      TS3SERVER_DB_PASSWORD: ${MYSQL_PASSWORD}
      TS3SERVER_DB_NAME: ${MYSQL_DATABASE}
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    volumes:
      - teamspeak-data:/var/ts3server/
    ports:
      - ${PROXY_PORT_9987}:9987/udp
      - ${PROXY_PORT_30033}:30033
      - ${PROXY_PORT_10011}:10011
